name: Auto Publicize Repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  check_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository Activity
        id: check_activity
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const sixMonthsAgo = new Date();
            sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
            const { data: repoDetails } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const repoUpdate = new Date(repoDetails.updated_at);
            console.log("is " + repoUpdate + " < " + sixMonthsAgo + " ?");
            const result = repoUpdate < sixMonthsAgo;
            console.log(result);
            return result;

      - name: Make Repository Public
        if: steps.check_activity.outputs.result == true
        run: |
          RESPONSE=$(curl -X PATCH \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"visibility":"public"}')
          if [ $RESPONSE -eq 200 ]; then
            echo "Repository visibility successfully changed to public."
          else
            echo "Failed to change repository visibility. HTTP response code: $RESPONSE"
          fi
